name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.41.2
  build: ^1.6.1
  code_builder: ^3.6.0
  collection: ^1.15.0-nullsafety.5
  dart_style: ^1.3.11
  logging: ^0.11.0
  meta: ^1.3.0-nullsafety.6
  path: ^1.8.0-nullsafety.3
  quiver: ^3.0.0-nullsafety.3
  stack_trace: ^1.10.0-nullsafety.6

dev_dependencies:
  build_runner: ^1.11.0
  build_test: ^1.3.4
  inject:
    path: ../inject
  test: ^1.15.7
